#                                                                        #
# Default subroutes configuration for the CostaBrava.User package        #
#                                                                        #

-
  name: 'Captcha'
  uriPattern:    'captcha122'
  defaults:
    '@package': 'Lelesys.Captcha'
    '@controller': 'captcha'
    '@action':  'captcha'

-
  name: 'New'
  uriPattern:    'new12'
  defaults:
    '@package': 'Lelesys.Captcha'
    '@controller': 'captcha'
    '@action':  'index'
