Lelesys:
  Captcha:
    customErrorMessagePackageKey: 'Lelesys.Captcha'
    errorMessageTextWrong: 'lelesys.captcha.textwrong'
    errorMessageTextNotFound: 'lelesys.captcha.notextfound'
    templatePath: 'resource://Lelesys.Captcha/Private/Templates/ViewHelper/Captcha.html'
    primaryColor:
      red: 0
      green: 0
      blue: 0
    distortion: 0
    interpolation: TRUE
    maxBehindLines: '1'
    maxFrontLines: '1'
    font: NULL
    height: 100
    width: 30
    caseSensitive: FALSE
Neos:
  Flow:
    mvc:
      routes:
        Lelesys.Captcha:
          position: 'before Neos.Neos'